### ISSUE TITLE
ArgoCD and microk8s

### ISSUE THREAD

**Issue by mikysal78** [capitanh/argocdk8s_ansible_role#1]
Hi,
I need to install ArgoCD and kubernets with ansible
On your role [microk8s_ansible_role](https://github.com/capitanh/microk8s_ansible_role), I did not see how to install master and nodes.
Does it work with debian 12?
Do you have a complete example paybook?

Best regards,
Michele

**Comment by capitanh** [comment]
Hi @mikysal78 :
This role (and the microk8s one) are mostly meant to be used as part of a local/test environment. I use them as a way of automatically provision a local virtual machine managed with vagrant which has proven to be a really useful way of testing things before applying them in a production cluster. No need to worry about nodes in such scenario, then. If you have had a chance to look at the microk8s role you should've seen that it uses snap to install microk8s system, so it will only work in Ubuntu, not in Debian.

**Comment by mikysal78** [comment]
thanks
